### ISSUE TITLE
MySQL / MariaDB 在创建表 path_meta 时无法使用 4096 长度的 path 作为主键

### ISSUE THREAD

**Issue by AndroidOL** [devld/go-drive#113]
```
[0.775ms] [rows:0] CREATE TABLE path_meta (path varchar(4096) NOT NULL,password varchar(64),default_sort varchar(32),default_mode varchar(32),hidden_pattern varchar(4096),recursive int unsigned NOT NULL,PRIMARY KEY (path))

2025/06/11 03:07:35 Error 1071 (42000): Specified key was too long; max key length is 3072 bytes
```

**Comment by AndroidOL** [comment]
> docker-compose.yml

```
services:
  godrive:
    image: devld/go-drive
    container_name: godrive
    ports:
      - "8089:8089"
    volumes:
      - ./go-drive-data:/app/data
      - ./config.yml:/app/config.yml
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql
    container_name: go-drive-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: AndroidOL
      MYSQL_DATABASE: godrive
      MYSQL_USER: godrive
      MYSQL_PASSWORD: godrive
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./go-drive-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
```
