### ISSUE TITLE
onedrive国际版挂载后访问盘出现提示“500 服务器错误”

### ISSUE THREAD

**Issue by fcki1984** [devld/go-drive#35]
## 描述
挂载国际版(A1教育版)后访问onedrive挂载盘出现错误 500 服务器错误，

Error #01: BadRequest: Resource not found for the segment 'v1.0'.

## config.yml（修改）

```
default-lang: zh-CN

proxy-max-size: 0 # 1M

free-fs: true

thumbnail:
  concurrent: 2

search:
  enabled: true
```
## nginx 反代
```
location /
{

    proxy_pass            http://127.0.0.1:8089; #端口保持一致
    proxy_set_header      Host $host;
    proxy_set_header      X-Real-IP $remote_addr;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header      REMOTE-HOST $remote_addr;
    proxy_buffering       off;
    proxy_cache           off;
    proxy_set_header      X-Forwarded-Proto $scheme;
}
	
```
## Azure
>除了账户类型选择了仅我的组织外，其他的都安装教程来的。

受支持的帐户类型
[仅我的组织]
