### ISSUE TITLE
修改目录权限后，Drive不显示了

### ISSUE THREAD

**Issue by Ansen** [devld/go-drive#38]
这样修改之后

![image](https://user-images.githubusercontent.com/676412/168759336-cff4284f-1342-4b60-b8d7-54043dec4f43.png)

列表丢失了

![image](https://user-images.githubusercontent.com/676412/168759697-07d6a571-a5e8-45b8-bc9c-8c30a90be555.png)

手动输入路径进入，报 Error #01: "error.permission_denied"

![image](https://user-images.githubusercontent.com/676412/168760064-1583907c-743e-4674-9d3f-e7750496dbfe.png)

> docker-compose.yml 

```
version: '3'
services:
  go-drive:
    image: devld/go-drive:latest
    container_name: go-drive
    ports:
      - 8089:8089
    volumes:
      -  /data/go-drive-data:/app/data
    restart: always
    privileged: true
```
